version: '3'
services:

  traefik:
    ports:
      - "8080:8080/tcp"
    command:
      - "--api.dashboard=true"
        #- "--api.insecure"
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik.log"
      - "--accessLog.filePath=/var/log/traefik_access.log"
      - "--accesslog.filters.statuscodes=201-599"
    volumes:
      - "./data/traefik/log/:/var/log"
